### PR TITLE
Relax the constraint of dependent version of multi_json

### PR DESCRIPTION
**Pull request by basex**

### CODE REVIEW

**Comment by jackfranklin** [comment]
Hey @basex, what's the reasoning behind this? Have you been having issues?

**Comment by basex** [comment]
I'm having issues with the update of several other gems because pusher is requiring a very old version of the gem. https://rubygems.org/gems/multi_json/versions

**Comment by jackfranklin** [comment]
Ah OK, thanks. I wonder if we should additionally look into bumping the version of the gem we use to bring it a bit more up to date. I might try that and see if the tests pass.

**Comment by basex** [comment]
You shouldn't have any problem up to the last version of the 1 series https://github.com/intridea/multi_json#versioning

**Comment by jackfranklin** [comment]
That's what I thought - do you fancy bumping the version in this PR? If the tests pass we should be all good to merge and I can push a new version out.

**Comment by basex** [comment]
I bumped. Is it ok now?

**Comment by jackfranklin** [comment]
I think so - but doesn't `~> 1.0` allow our gem to depend on any 1.X release? Or have I misunderstood ? We're wary of this change affecting users who might be on older gems.

**Comment by zimbatm** [comment]
The `~>` operator allows any version from 1.0 until 2.0 so it should be fine.

Can you paste the error that you were having ?

**Comment by basex** [comment]
Sorry, you are right. My problem was not coming from from the multi_json requirement in this gem.

**Pull request closed without merging**
